services:
  app:
    image: $APP_IMAGE_NAME:$VERSION

    container_name: $APP_CONTAINER_NAME
    env_file:
      - ./envs/app.env
  
  nginx:
    depends_on:
      - app
    image: $PROXY_IMAGE_NAME:$VERSION
    container_name: $PROXY_CONTAINER_NAME
    ports:
      - $APP_PROXY_PORT:80